apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-pre-install-hook
  labels:
    app: {{ .Release.Name }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  backoffLimit: 0
  template:
    metadata:
      name: {{ .Release.Name }}-pre-install-hook
      labels:
        app: {{ .Release.Name }}
    spec:
      restartPolicy: Never
      containers:
      - name: pre-install-job
        image: busybox:1.35
        command:
        - sh
        - -c
        - |
          echo "Pre-install hook started"
          echo "Simulating failure condition..."
          echo "ERROR: Pre-installation validation failed!"
          exit 1
